{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./chromium.nix
    ./git.nix
    ./hyprland
    ./lazygit.nix
    ./obsidian.nix
    ./stylix.nix
    ./swaync
    ./tmux.nix
    ./waybar
    ./wofi
    ./kitty.nix
    ./vscode.nix
    ./neovim.nix
    ./editor
    ./editor/helix.nix
    ./wezterm.nix
    ./fastfetch
    ./programming.nix
    ./rmpc
   ];
}
